version: "3.6"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local


services:
  # jupyterlab:
  #   image: jupyterlab
  #   container_name: jupyterlab
  #   ports:
  #     - 8888:8888
  #   volumes:
  #     - "./shared-workspace:/opt/workspace"
  #     - "./input:/input"
  #     - "./output:/output"


  ## spark master container
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
      - 4043:4040
    volumes:
      - "./shared_workspace:/opt/workspace"
      - "./input:/opt/input"
      - "./output:/opt/output"
  
  ## spark worker container
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - "./shared_workspace:/opt/workspace"
      - "./input:/opt/input"
      - "./output:/opt/output"
    depends_on:
      - spark-master

  ## spark client container
  spark-client:
    image: spark-worker
    container_name: spark-client
    ports:
      - 8083:8081
      - 7078:7077
    volumes:
      - ./shared_workspace:/opt/workspace
    depends_on:
      - spark-master

  ## aws lambda container for API 
  aws-lambda-python:
    image : aws-python-lambda
    container_name: aws-python-lambda-api
    ports:
      - 9000:8080
    volumes:
      - "./shared_workspace:/var/task"
    depends_on:
      - spark-master